### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by RafikFarhad** [RafikFarhad/hello-stack-overflow#1]
- [ ] Copy to daily cron
- [ ] Download latest chromedriver automatically
- [ ] Write test + CI Integration
- [ ] Observe
- [ ] Release
